### ISSUE TITLE
get next set of pagination results

### ISSUE THREAD

**Issue by Kop4lyf** [ryanseys/node-jawbone-up#11]
In getting the list of multiple events, we are getting a set of 10 previous events. If we need to get the set of next 10 events, how do we call that?

Thanks for the plugin. Good work.

**Comment by nyquist212** [comment]
I'm also facing this challenge. Anyone have a solution?

**Comment by ryanseys** [comment]
The response from the API will give you a `next` link in the `links` section. You take that value and pass it into the `page_token` parameter of your API call to get the next page. Take a look at the `page_token` parameter here: https://jawbone.com/up/developer/endpoints/moves

**Comment by ryanseys** [comment]
Oops! I mis-spoke. You need to just pass the `page_token` in that `next` link into the `page_token` of the request. This will require you to parse out the next `page_token` from that `next` link.

**Comment by nyquist212** [comment]
Strange...

I'm pretty sure I have sleep results going back beyond these initial 10 results but I'm not getting a next_page token in my1st page of paginated results...

"links": {
      "next": "/nudge/api/v.1.0/users/jMdCUPXZ-InYXo1kcdOkvA/sleeps?start_time=1424610901&updated_after=0&limit=10&end_time=1438638109"
    },
    "size": 10

**Comment by ryanseys** [comment]
Maybe that's a mistake in their docs. It's just a timestamp, so try to provide either the start_time or end_time.

**Comment by nyquist212** [comment]
This has been a real head-scratcher for a few weeks now... I'm doing something like this -

```
var $today      = new Date()
var $start      = new Date($today); $start.setDate($today.getDate() - 180);
var $end        = new Date($today);
var $startDate  = Math.floor(($start).getTime()/1000);
var $endDate    = Math.floor(($end).getTime()/1000);

{...snip...}

        do {

            up.sleeps.get({
                page_token :   page_token,
                start_time :   $startDate,
                end_time   :   $endDate
            }, function(err, body) {
        
                if (err) {
                    console.log('Error receiving Jawbone UP data');
                    // Something here to refresh access_token
                       res.send(err);
                } else {
                    try {
                        var result = JSON.parse(body);

                        var next_page_path = result.data.links.next;
                        //var next_page_token = next_page_path.split(path.sep);
                        //var page_token  = next_page_token[5];
                        page_token = result.data.links.next
                        console.log(result.data);
                        
                        res.json(result);

                    } // end try
                    catch(err) {
                        console.log(err);
                        res.render('userdata', {
                            requestTime: 0,
                            jawboneData: 'Unknown result'
                            });
                    } // end catch(err)
                    } // end else
                }  //end callback fun
            ); // end up.sleeps.get()

    } // end do
    while(page_token[0] > 1);
```
I've tried pretty much every combination of args and still only get the first page of paginated results. The JB docs are pretty opaque on the subject saying only it's an INT timestamp. Google has very little to offer on the subject and the JB "Developer Forum" is deserted.

My goal is to get the json back so I can feed it to D3.js

I'll continue tinkering but would love to hear from anyone if they have any insight or manage to get this working.

Rgds

**Comment by nyquist212** [comment]
SOLUTION: There is an undocumented "limit" parameter that appear to have replaced the "page_token". At the time of writing this, the dev documentation is not up to date.
